import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, writeFile, mkdir, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import {
  loadSidecarSnapshot,
  filterTargets,
  writeSidecarEdits,
  scanGallery,
  countByFilter,
  collectAllTags,
  collectAllLocations,
  type SidecarEditTarget,
  type SidecarFilter,
} from '../src/sidecar-edit.js';

function makeTarget(
  overrides: Partial<SidecarEditTarget> = {},
): SidecarEditTarget {
  return {
    photoPath: '/tmp/test.jpg',
    sidecarPath: '/tmp/test.yaml',
    gallerySlug: 'sample',
    filename: 'test.jpg',
    currentValues: {
      title: '',
      location: '',
      caption: '',
      tags: [],
    },
    ...overrides,
  };
}

describe('loadSidecarSnapshot', () => {
  it('parses a well-formed sidecar', () => {
    const content = `# Auto-generated by Obscura — feel free to edit
title: Red Umbrella
date: 2022-07-14
camera: LEICA Q2
lens: SUMMILUX 28mm
location: Baltic Sea, Germany
caption: A lone figure with a red umbrella.
tags:
  - baltic sea
  - moody
`;
    const snapshot = loadSidecarSnapshot(content);
    expect(snapshot.title).toBe('Red Umbrella');
    expect(snapshot.location).toBe('Baltic Sea, Germany');
    expect(snapshot.caption).toBe('A lone figure with a red umbrella.');
    expect(snapshot.tags).toEqual(['baltic sea', 'moody']);
    expect(snapshot.camera).toBe('LEICA Q2');
    expect(snapshot.lens).toBe('SUMMILUX 28mm');
    expect(snapshot.date).toEqual(new Date('2022-07-14'));
  });

  it('handles missing fields gracefully', () => {
    const content = `title: ""
location: ""
caption: ""
tags: []
`;
    const snapshot = loadSidecarSnapshot(content);
    expect(snapshot.title).toBe('');
    expect(snapshot.location).toBe('');
    expect(snapshot.caption).toBe('');
    expect(snapshot.tags).toEqual([]);
    expect(snapshot.camera).toBeUndefined();
    expect(snapshot.date).toBeUndefined();
    expect(snapshot.lens).toBeUndefined();
  });

  it('handles empty/null content', () => {
    const snapshot = loadSidecarSnapshot('');
    expect(snapshot.title).toBe('');
    expect(snapshot.tags).toEqual([]);
  });

  it('handles minimal sidecar with only some fields', () => {
    const content = `title: Test
tags:
  - foo
`;
    const snapshot = loadSidecarSnapshot(content);
    expect(snapshot.title).toBe('Test');
    expect(snapshot.location).toBe('');
    expect(snapshot.tags).toEqual(['foo']);
  });
});

describe('filterTargets', () => {
  const targets: readonly SidecarEditTarget[] = [
    makeTarget({
      filename: 'a.jpg',
      currentValues: {
        title: 'Has Title',
        location: '',
        caption: '',
        tags: [],
      },
    }),
    makeTarget({
      filename: 'b.jpg',
      currentValues: {
        title: '',
        location: 'Berlin',
        caption: 'A caption',
        tags: ['tag1'],
      },
    }),
    makeTarget({
      filename: 'c.jpg',
      currentValues: {
        title: '',
        location: '',
        caption: '',
        tags: [],
      },
    }),
  ];

  it('returns all targets for "all" filter', () => {
    const filter: SidecarFilter = { field: 'all' };
    expect(filterTargets(targets, filter)).toHaveLength(3);
  });

  it('filters by missing title', () => {
    const filter: SidecarFilter = { field: 'title' };
    const result = filterTargets(targets, filter);
    expect(result).toHaveLength(2);
    expect(result[0]!.filename).toBe('b.jpg');
    expect(result[1]!.filename).toBe('c.jpg');
  });

  it('filters by missing location', () => {
    const filter: SidecarFilter = { field: 'location' };
    const result = filterTargets(targets, filter);
    expect(result).toHaveLength(2);
    expect(result[0]!.filename).toBe('a.jpg');
    expect(result[1]!.filename).toBe('c.jpg');
  });

  it('filters by missing caption', () => {
    const filter: SidecarFilter = { field: 'caption' };
    const result = filterTargets(targets, filter);
    expect(result).toHaveLength(2);
    expect(result[0]!.filename).toBe('a.jpg');
    expect(result[1]!.filename).toBe('c.jpg');
  });

  it('filters by missing tags', () => {
    const filter: SidecarFilter = { field: 'tags' };
    const result = filterTargets(targets, filter);
    expect(result).toHaveLength(2);
    expect(result[0]!.filename).toBe('a.jpg');
    expect(result[1]!.filename).toBe('c.jpg');
  });

  it('returns empty array when no matches', () => {
    const allComplete: readonly SidecarEditTarget[] = [
      makeTarget({
        currentValues: {
          title: 'Yes',
          location: 'Here',
          caption: 'Something',
          tags: ['x'],
        },
      }),
    ];
    const filter: SidecarFilter = { field: 'title' };
    expect(filterTargets(allComplete, filter)).toHaveLength(0);
  });
});

describe('countByFilter', () => {
  it('counts correctly', () => {
    const targets: readonly SidecarEditTarget[] = [
      makeTarget({
        currentValues: { title: '', location: 'A', caption: '', tags: ['x'] },
      }),
      makeTarget({
        currentValues: { title: 'B', location: '', caption: 'C', tags: [] },
      }),
    ];
    const counts = countByFilter(targets);
    expect(counts.all).toBe(2);
    expect(counts.title).toBe(1);
    expect(counts.location).toBe(1);
    expect(counts.caption).toBe(1);
    expect(counts.tags).toBe(1);
  });
});

describe('writeSidecarEdits', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await mkdtemp(join(tmpdir(), 'obscura-test-'));
  });

  afterEach(async () => {
    await rm(tmpDir, { recursive: true });
  });

  it('round-trips YAML preserving comments and untouched fields', async () => {
    const sidecarPath = resolve(tmpDir, 'test.yaml');
    const original = `# Auto-generated by Obscura — feel free to edit
title: ""
date: 2022-07-14
camera: LEICA Q2
lens: SUMMILUX 28mm
gps_lat:
gps_lon:
location: ""
caption: ""
tags: []
`;
    await writeFile(sidecarPath, original, 'utf-8');

    await writeSidecarEdits(sidecarPath, {
      title: 'Red Umbrella',
      location: 'Baltic Sea',
    });

    const result = await readFile(sidecarPath, 'utf-8');
    expect(result).toContain('# Auto-generated by Obscura');
    expect(result).toContain('Red Umbrella');
    expect(result).toContain('Baltic Sea');
    // Untouched fields preserved
    expect(result).toContain('camera: LEICA Q2');
    expect(result).toContain('date: 2022-07-14');
    // Verify the values parse correctly via round-trip
    const snapshot = loadSidecarSnapshot(result);
    expect(snapshot.title).toBe('Red Umbrella');
    expect(snapshot.location).toBe('Baltic Sea');
    expect(snapshot.camera).toBe('LEICA Q2');
  });

  it('writes tags as YAML array', async () => {
    const sidecarPath = resolve(tmpDir, 'test.yaml');
    const original = `title: ""
tags: []
`;
    await writeFile(sidecarPath, original, 'utf-8');

    await writeSidecarEdits(sidecarPath, {
      tags: ['baltic sea', 'moody'],
    });

    const result = await readFile(sidecarPath, 'utf-8');
    expect(result).toContain('baltic sea');
    expect(result).toContain('moody');
  });

  it('only writes provided fields (partial edits)', async () => {
    const sidecarPath = resolve(tmpDir, 'test.yaml');
    const original = `title: Original Title
location: Original Location
caption: Original Caption
tags:
  - original
`;
    await writeFile(sidecarPath, original, 'utf-8');

    await writeSidecarEdits(sidecarPath, {
      caption: 'New Caption',
    });

    const result = await readFile(sidecarPath, 'utf-8');
    expect(result).toContain('title: Original Title');
    expect(result).toContain('location: Original Location');
    expect(result).toContain('caption: New Caption');
    expect(result).toContain('original');
  });
});

describe('scanGallery', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await mkdtemp(join(tmpdir(), 'obscura-scan-'));
  });

  afterEach(async () => {
    await rm(tmpDir, { recursive: true });
  });

  it('lists photo files with their sidecar snapshots', async () => {
    const galleryDir = resolve(tmpDir, 'test-gallery');
    await mkdir(galleryDir);
    // Create photo files (just empty files for testing)
    await writeFile(resolve(galleryDir, 'photo1.jpg'), '');
    await writeFile(resolve(galleryDir, 'photo2.png'), '');
    // Create a sidecar for photo1
    await writeFile(
      resolve(galleryDir, 'photo1.yaml'),
      'title: Hello\nlocation: Berlin\ncaption: ""\ntags: []\n',
    );
    // Non-photo file should be ignored
    await writeFile(resolve(galleryDir, 'readme.txt'), 'ignore me');

    const targets = await scanGallery(galleryDir, 'test-gallery');
    expect(targets).toHaveLength(2);

    const photo1 = targets.find((t) => t.filename === 'photo1.jpg');
    expect(photo1).toBeDefined();
    expect(photo1!.currentValues.title).toBe('Hello');
    expect(photo1!.currentValues.location).toBe('Berlin');
    expect(photo1!.gallerySlug).toBe('test-gallery');

    const photo2 = targets.find((t) => t.filename === 'photo2.png');
    expect(photo2).toBeDefined();
    expect(photo2!.currentValues.title).toBe('');
  });

  it('returns empty array for non-existent directory', async () => {
    const targets = await scanGallery('/nonexistent/path', 'none');
    expect(targets).toHaveLength(0);
  });

  it('computes correct paths', async () => {
    const galleryDir = resolve(tmpDir, 'gallery');
    await mkdir(galleryDir);
    await writeFile(resolve(galleryDir, 'img.jpg'), '');

    const targets = await scanGallery(galleryDir, 'slug');
    expect(targets).toHaveLength(1);
    expect(targets[0]!.photoPath).toBe(resolve(galleryDir, 'img.jpg'));
    expect(targets[0]!.sidecarPath).toBe(resolve(galleryDir, 'img.yaml'));
    expect(targets[0]!.filename).toBe('img.jpg');
    expect(targets[0]!.gallerySlug).toBe('slug');
  });
});

describe('collectAllTags', () => {
  it('collects unique tags across multiple targets', () => {
    const targets = [
      makeTarget({
        currentValues: { title: '', location: '', caption: '', tags: ['a', 'b'] },
      }),
      makeTarget({
        currentValues: { title: '', location: '', caption: '', tags: ['c'] },
      }),
    ];
    expect(collectAllTags(targets)).toEqual(['a', 'b', 'c']);
  });

  it('returns sorted array', () => {
    const targets = [
      makeTarget({
        currentValues: { title: '', location: '', caption: '', tags: ['zebra', 'apple'] },
      }),
    ];
    expect(collectAllTags(targets)).toEqual(['apple', 'zebra']);
  });

  it('returns empty array when no targets have tags', () => {
    const targets = [
      makeTarget(),
      makeTarget(),
    ];
    expect(collectAllTags(targets)).toEqual([]);
  });

  it('deduplicates tags that appear on multiple photos', () => {
    const targets = [
      makeTarget({
        currentValues: { title: '', location: '', caption: '', tags: ['moody', 'street'] },
      }),
      makeTarget({
        currentValues: { title: '', location: '', caption: '', tags: ['moody', 'landscape'] },
      }),
    ];
    expect(collectAllTags(targets)).toEqual(['landscape', 'moody', 'street']);
  });
});

describe('collectAllLocations', () => {
  it('collects unique locations across targets', () => {
    const targets = [
      makeTarget({
        currentValues: { title: '', location: 'Berlin', caption: '', tags: [] },
      }),
      makeTarget({
        currentValues: { title: '', location: 'Paris', caption: '', tags: [] },
      }),
    ];
    expect(collectAllLocations(targets)).toEqual(['Berlin', 'Paris']);
  });

  it('returns sorted array', () => {
    const targets = [
      makeTarget({
        currentValues: { title: '', location: 'Zurich', caption: '', tags: [] },
      }),
      makeTarget({
        currentValues: { title: '', location: 'Amsterdam', caption: '', tags: [] },
      }),
    ];
    expect(collectAllLocations(targets)).toEqual(['Amsterdam', 'Zurich']);
  });

  it('skips empty location strings', () => {
    const targets = [
      makeTarget({
        currentValues: { title: '', location: '', caption: '', tags: [] },
      }),
      makeTarget({
        currentValues: { title: '', location: 'Berlin', caption: '', tags: [] },
      }),
    ];
    expect(collectAllLocations(targets)).toEqual(['Berlin']);
  });

  it('deduplicates locations appearing on multiple photos', () => {
    const targets = [
      makeTarget({
        currentValues: { title: '', location: 'Berlin', caption: '', tags: [] },
      }),
      makeTarget({
        currentValues: { title: '', location: 'Berlin', caption: '', tags: [] },
      }),
      makeTarget({
        currentValues: { title: '', location: 'Paris', caption: '', tags: [] },
      }),
    ];
    expect(collectAllLocations(targets)).toEqual(['Berlin', 'Paris']);
  });

  it('returns empty array when no targets have locations', () => {
    const targets = [
      makeTarget(),
      makeTarget(),
    ];
    expect(collectAllLocations(targets)).toEqual([]);
  });
});
