import * as cheerio from 'cheerio';
import type { EnumeratedUrls } from './types.js';

/**
 * Parse a sitemap.xml and categorise its URLs against a known base URL.
 * Tag and location URLs are dropped — they're regenerated by the local build.
 */
export function categoriseSitemap(
  sitemapXml: string,
  baseUrl: string,
): EnumeratedUrls {
  const $ = cheerio.load(sitemapXml, { xmlMode: true });
  const urls: string[] = [];
  $('url > loc').each((_, el) => {
    const text = $(el).text().trim();
    if (text.length > 0) urls.push(text);
  });

  const base = baseUrl.replace(/\/+$/u, '');
  const pathOf = (u: string): string => {
    if (!u.startsWith(base)) return '';
    return u.slice(base.length) || '/';
  };

  let homepage = '';
  let galleryIndex: string | null = null;
  const galleries: string[] = [];
  const photos: string[] = [];
  const posts: string[] = [];
  const pages: string[] = [];

  for (const url of urls) {
    const path = pathOf(url);
    if (path === '') continue;
    if (path === '/') {
      homepage = url;
      continue;
    }
    if (path === '/photography/') {
      galleryIndex = url;
      continue;
    }
    if (path === '/blog/' || path === '/tags/' || path === '/locations/') {
      continue;
    }
    if (path.startsWith('/tags/') || path.startsWith('/locations/')) {
      continue;
    }
    const photoMatch = /^\/photography\/([^/]+)\/([^/]+)\/$/u.exec(path);
    if (photoMatch) {
      photos.push(url);
      continue;
    }
    const galleryMatch = /^\/photography\/([^/]+)\/$/u.exec(path);
    if (galleryMatch) {
      galleries.push(url);
      continue;
    }
    if (path.startsWith('/blog/')) {
      posts.push(url);
      continue;
    }
    // anything else at the top level is a Page
    if (/^\/[^/]+\/$/u.test(path)) {
      pages.push(url);
      continue;
    }
  }

  if (homepage === '') {
    throw new Error(
      `sitemap did not contain a homepage URL for base ${baseUrl}`,
    );
  }

  return { homepage, galleryIndex, galleries, photos, posts, pages };
}
