import type {
  SiteConfig,
  GalleryEntry,
  PhotoMetadata,
  BlogPostFrontmatter,
  PageFrontmatter,
} from '../types.js';

/** A warning generated by any parser. Aggregated into recovery-report.md. */
export interface RecoveryWarning {
  readonly category:
    | 'identify'
    | 'site'
    | 'gallery'
    | 'photo'
    | 'post'
    | 'page'
    | 'image'
    | 'sitemap';
  readonly subject: string;
  readonly message: string;
}

/** Output of the identify stage. */
export interface Identified {
  /** Theme name. Defaults to 'editorial' when data-theme is absent. */
  readonly theme: string;
  /** Obscura version that built the upstream site, or null when data-version is absent. */
  readonly version: string | null;
  /** Build timestamp from the content attribute, or null if unparseable. */
  readonly buildTimestamp: string | null;
  /** True when fallbacks were applied. */
  readonly usedFallback: boolean;
  readonly warnings: readonly RecoveryWarning[];
}

/** Output of the sitemap enumeration stage. */
export interface EnumeratedUrls {
  readonly homepage: string;
  readonly galleryIndex: string | null;
  readonly galleries: readonly string[];
  readonly photos: readonly string[];
  readonly posts: readonly string[];
  readonly pages: readonly string[];
}

/** Subset of SiteConfig recoverable from a homepage. Everything optional except a few essentials. */
export type RecoveredSiteConfig = Partial<SiteConfig> & {
  readonly theme: string;
  readonly base_url: string;
  readonly title: string;
};

export interface ParseResult<T> {
  readonly value: T;
  readonly warnings: readonly RecoveryWarning[];
}

export interface ParsedPhoto {
  readonly gallerySlug: string;
  readonly photoSlug: string;
  readonly metadata: Partial<PhotoMetadata>;
  /** Absolute URL of the largest image variant available, or null if none. */
  readonly imageUrl: string | null;
  /** File extension derived from imageUrl, e.g. ".jpg". */
  readonly imageExt: string | null;
}

export interface ParsedGallery {
  readonly entry: GalleryEntry;
}

export interface ParsedPost {
  readonly slug: string;
  readonly frontmatter: Partial<BlogPostFrontmatter>;
  readonly markdownBody: string;
  /** True if Turndown threw; markdownBody will be empty and rawHtml will be set. */
  readonly conversionFailed: boolean;
  readonly rawHtml?: string;
}

export interface ParsedPage {
  readonly slug: string;
  readonly frontmatter: Partial<PageFrontmatter>;
  readonly markdownBody: string;
  readonly conversionFailed: boolean;
  readonly rawHtml?: string;
}
