base_url: https://coma.photography
title: "Obscura - A Static Site Generator for Photographers only"
theme: editorial
recent_shots_count: 10
images:
  breakpoints: [400, 800, 1200, 2400]
  webp_quality: 85
