import { describe, it, expect } from 'vitest';
import { categoriseSitemap } from '../../src/recover/sitemap.js';

const SITEMAP = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>https://example.com/</loc></url>
  <url><loc>https://example.com/photography/</loc></url>
  <url><loc>https://example.com/photography/sample/</loc></url>
  <url><loc>https://example.com/photography/sample/sample-01/</loc></url>
  <url><loc>https://example.com/photography/sample/sample-02/</loc></url>
  <url><loc>https://example.com/blog/</loc></url>
  <url><loc>https://example.com/blog/welcome/</loc></url>
  <url><loc>https://example.com/about/</loc></url>
  <url><loc>https://example.com/contact/</loc></url>
  <url><loc>https://example.com/tags/</loc></url>
  <url><loc>https://example.com/tags/landscape/</loc></url>
  <url><loc>https://example.com/locations/</loc></url>
  <url><loc>https://example.com/locations/hamburg/</loc></url>
</urlset>`;

describe('categoriseSitemap', () => {
  it('separates URLs into the expected categories', () => {
    const result = categoriseSitemap(SITEMAP, 'https://example.com');
    expect(result.homepage).toBe('https://example.com/');
    expect(result.galleryIndex).toBe('https://example.com/photography/');
    expect(result.galleries).toEqual([
      'https://example.com/photography/sample/',
    ]);
    expect(result.photos).toEqual([
      'https://example.com/photography/sample/sample-01/',
      'https://example.com/photography/sample/sample-02/',
    ]);
    expect(result.posts).toEqual(['https://example.com/blog/welcome/']);
    expect(result.pages).toEqual([
      'https://example.com/about/',
      'https://example.com/contact/',
    ]);
  });

  it('handles a base_path subdirectory deploy', () => {
    const sm = SITEMAP.replaceAll('example.com/', 'example.com/portfolio/');
    const result = categoriseSitemap(sm, 'https://example.com/portfolio');
    expect(result.photos[0]).toBe(
      'https://example.com/portfolio/photography/sample/sample-01/',
    );
    expect(result.pages).toEqual([
      'https://example.com/portfolio/about/',
      'https://example.com/portfolio/contact/',
    ]);
  });

  it('ignores tag and location URLs (regenerated by build)', () => {
    const result = categoriseSitemap(SITEMAP, 'https://example.com');
    expect(result.pages).not.toContain('https://example.com/tags/landscape/');
    expect(result.pages).not.toContain(
      'https://example.com/locations/hamburg/',
    );
  });
});
