import { readdir, access, writeFile } from 'node:fs/promises';
import { resolve, extname } from 'node:path';
import { stringify as stringifyYaml } from 'yaml';
import type { ExifData } from './types.js';
import { readExif } from './exif.js';
import type { ExifWarning } from './exif.js';

const SUPPORTED_EXTENSIONS = new Set([
  '.jpg',
  '.jpeg',
  '.png',
  '.tiff',
  '.tif',
  '.webp',
]);

const SIDECAR_HEADER = '# Auto-generated by Obscura — feel free to edit\n';

interface SidecarTemplate {
  title: string;
  date: string | null;
  camera: string | null;
  lens: string | null;
  focal_length: number | null;
  iso: number | null;
  aperture: number | null;
  shutter_speed: string | null;
  gps_lat: number | null;
  gps_lon: number | null;
  location: string;
  caption: string;
  tags: string[];
}

function formatDate(date: Date): string {
  return date.toISOString().split('T')[0] ?? '';
}

function buildSidecarTemplate(exif: ExifData): SidecarTemplate {
  return {
    title: 'Untitled',
    date: exif.date ? formatDate(exif.date) : null,
    camera: exif.camera ?? null,
    lens: exif.lens ?? null,
    focal_length: exif.focal_length ?? null,
    iso: exif.iso ?? null,
    aperture: exif.aperture ?? null,
    shutter_speed: exif.shutter_speed ?? null,
    gps_lat: exif.gps_lat ?? null,
    gps_lon: exif.gps_lon ?? null,
    location: '',
    caption: '',
    tags: [],
  };
}

function sidecarToYaml(template: SidecarTemplate): string {
  const yamlContent = stringifyYaml(template, {
    nullStr: '',
    lineWidth: 0,
  });
  return SIDECAR_HEADER + yamlContent;
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

export function isPhotoFile(filename: string): boolean {
  return SUPPORTED_EXTENSIONS.has(extname(filename).toLowerCase());
}

export function sidecarPathForPhoto(photoPath: string): string {
  const ext = extname(photoPath);
  return photoPath.slice(0, -ext.length) + '.yaml';
}

export interface GenerateSidecarsResult {
  readonly generated: readonly string[];
  readonly warnings: readonly ExifWarning[];
}

export async function generateSidecars(
  galleryDir: string,
): Promise<GenerateSidecarsResult> {
  let entries: string[];
  try {
    const dirEntries = await readdir(galleryDir);
    entries = dirEntries.filter(isPhotoFile);
  } catch {
    return { generated: [], warnings: [] };
  }

  const generated: string[] = [];
  const warnings: ExifWarning[] = [];

  for (const entry of entries) {
    const photoPath = resolve(galleryDir, entry);
    const sidecarPath = sidecarPathForPhoto(photoPath);

    if (await fileExists(sidecarPath)) {
      continue;
    }

    const exifResult = await readExif(photoPath);
    if (exifResult.warning) {
      warnings.push(exifResult.warning);
    }

    const template = buildSidecarTemplate(exifResult.data);
    const yamlContent = sidecarToYaml(template);
    await writeFile(sidecarPath, yamlContent, 'utf-8');
    generated.push(sidecarPath);
  }

  return { generated, warnings };
}

export async function generateAllSidecars(
  photosDir: string,
  gallerySlugs: readonly string[],
): Promise<GenerateSidecarsResult> {
  const allGenerated: string[] = [];
  const allWarnings: ExifWarning[] = [];

  for (const slug of gallerySlugs) {
    const galleryDir = resolve(photosDir, slug);
    const result = await generateSidecars(galleryDir);
    allGenerated.push(...result.generated);
    allWarnings.push(...result.warnings);
  }

  return { generated: allGenerated, warnings: allWarnings };
}
